files: 'mapclassify\/'
repos:
  - repo: https://github.com/psf/black
    rev: "24.4.2"
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.5.0"
    hooks:
      - id: ruff

ci:
  autofix_prs: false
  autoupdate_schedule: quarterly
